### PR TITLE
Update fr_fr.json

### PR DESCRIPTION
**Pull request by Fraonil**
Hello, here is a small contribution, for this great mod! I hope my translation will be suitable, I tried to take into account Create's FR translations to make it look the same. 

This is my first contribution on github I hope I'm doing it the right way.

See you !

### CODE REVIEW

**Comment by iglee42** [comment]
Hello did you used Google Translate or are you french because some translation are strange

**Comment by Fraonil** [comment]
Hi, I'm French what translation ? We can discuss it

**Comment by iglee42** [comment]
After rechecking it's all good

**Review by iglee42 — APPROVED** [review]
Ok, next time do the pull request on the dev branch

**Comment by Fraonil** [comment]
Cool, yes sorry. I'm improve it for the next time !

**Pull request merged**
