### PR TITLE
fixing god awful spelling and grammar

### PR DESCRIPTION
**Pull request by AfkUserMC**
so players can understand it better

### CODE REVIEW

**Review by APie357 — APPROVED** [review]
~~slightly~~ better grammar

**Review by iglee42 — CHANGES_REQUESTED** [review]
For mixers summaries please change "rotational force" to stress please

**Comment by AfkUserMC** [comment]
> For mixers summaries please change "rotational force" to stress please

done

**Review by iglee42 — APPROVED** [review]

**Comment by iglee42** [comment]
Change the pull request to 1.20.1/dev branch please

**Comment by AfkUserMC** [comment]
> Change the pull request to 1.20.1/dev branch please

made a new pr, we'll see if that works

**Comment by iglee42** [comment]
I will merge on main and after I will put modifications on dev branch

**Comment by AfkUserMC** [comment]
> I will merge on main and after I will put modifications on dev branch

sounds good, should i close #43 ?

**Comment by iglee42** [comment]
Yes you can

**Pull request merged**
